spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

seata:
  config:
    consul:
      server-addr: localhost:8500
  registry:
    consul:
      server-addr: localhost:8500
  tx-service-group: tx_group
  service:
    vgroup-mapping:
      tx_group: seata-group
    grouplist:
      seata-group: 127.0.0.1:8091
